export {navPage} from './navigate'
export {logPage} from './login'
export {regPage} from './reg'
export {error404} from './error404'
export {error500} from './error500'
export {profile} from './profile'